[[obj]]
    id = "sovsh_floor"
    pos = [1.25, 0.0, 1.25]

[[obj]]
    id = "sovsh_floor"
    pos = [1.25, 0.0, 3.75]
    
[[obj]]
    id = "sovsh_floor"
    pos = [3.75, 0.0, 1.25]

[[obj]]
    id = "sovsh_floor"
    pos = [3.75, 0.0, 3.75]

[[obj]]
    id = "sovsh_floor"
    pos = [6.25, 0.0, 1.25]

[[obj]]
    id = "sovsh_floor"
    pos = [6.25, 0.0, 3.75]
