
# ------ Floor ------
[[obj]]
    id = "sovsh_floor"
    pos = [1.25, 0.0, 1.25]

[[obj]]
    id = "sovsh_floor"
    pos = [1.25, 0.0, 3.75]
    
[[obj]]
    id = "sovsh_floor"
    pos = [3.75, 0.0, 1.25]

[[obj]]
    id = "sovsh_floor"
    pos = [3.75, 0.0, 3.75]

[[obj]]
    id = "sovsh_floor"
    pos = [6.25, 0.0, 1.25]

[[obj]]
    id = "sovsh_floor"
    pos = [6.25, 0.0, 3.75]

# ------ Ceiling ------
[[obj]]
    id = "sovsh_ceil01"
    pos = [1.25, 2.5, 1.25]
    rot = [0.0, 180.0, 0.0]

[[obj]]
    id = "sovsh_ceil01"
    pos = [1.25, 2.5, 3.75]
    rot = [0.0, -90.0, 0.0]
    
[[obj]]
    id = "sovsh_ceil02"
    pos = [3.75, 2.5, 1.25]
    rot = [0.0, 90.0, 0.0]

[[obj]]
    id = "sovsh_ceil02"
    pos = [3.75, 2.5, 3.75]
    rot = [0.0, -90.0, 0.0]

[[obj]]
    id = "sovsh_ceil01"
    pos = [6.25, 2.5, 1.25]
    rot = [0.0, 90.0, 0.0]

[[obj]]
    id = "sovsh_ceil01"
    pos = [6.25, 2.5, 3.75]
    rot = [0.0, 0.0, 0.0]

# ------ Ceiling ------
[[obj]]
    id = "sovsh_wall"
    pos = [0.0, 0.0, 1.25]
    rot = [0.0, -90.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [0.0, 0.0, 3.75]
    rot = [0.0, -90.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [1.25, 0.0, 0.0]
    rot = [0.0, 180.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [3.75, 0.0, 0.0]
    rot = [0.0, 180.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [6.25, 0.0, 0.0]
    rot = [0.0, 180.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [1.25, 0.0, 5.0]
    rot = [0.0, 0.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [3.75, 0.0, 5.0]
    rot = [0.0, 0.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [6.25, 0.0, 5.0]
    rot = [0.0, 0.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [7.5, 0.0, 1.25]
    rot = [0.0, 90.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [7.5, 0.0, 3.75]
    rot = [0.0, 90.0, 0.0]

# ------ Furniture ------
[[obj]]
    id = "diesel_gen"
    pos = [3.5, 0.0, 4.0]

[[obj]]
    id = "chair"
    pos = [0.5, 0.0, 3.0]
    rot = [0.0, 122.0, 0.0]
