
# ------ Floor ------
# Room 1
[[obj]]
    id = "sovsh_floor"
    pos = [1.25, 0.0, 1.25]

[[obj]]
    id = "sovsh_floor"
    pos = [1.25, 0.0, 3.75]
    
[[obj]]
    id = "sovsh_floor"
    pos = [3.75, 0.0, 1.25]

[[obj]]
    id = "sovsh_floor"
    pos = [3.75, 0.0, 3.75]

[[obj]]
    id = "sovsh_floor"
    pos = [6.25, 0.0, 1.25]

[[obj]]
    id = "sovsh_floor"
    pos = [6.25, 0.0, 3.75]

# Room 2
[[obj]]
    id = "sovsh_floor"
    pos = [3.75, 0.0, 6.65]

[[obj]]
    id = "sovsh_floor"
    pos = [3.75, 0.0, 9.15]

[[obj]]
    id = "sovsh_floor"
    pos = [6.25, 0.0, 6.65]

[[obj]]
    id = "sovsh_floor"
    pos = [6.25, 0.0, 9.15]

# ------ Ceiling ------
[[obj]]
    id = "sovsh_ceil01"
    pos = [1.25, 2.5, 1.25]
    rot = [0.0, 180.0, 0.0]

[[obj]]
    id = "sovsh_ceil01"
    pos = [1.25, 2.5, 3.75]
    rot = [0.0, -90.0, 0.0]
    
[[obj]]
    id = "sovsh_ceil02"
    pos = [3.75, 2.5, 1.25]
    rot = [0.0, 90.0, 0.0]

[[obj]]
    id = "sovsh_ceil02"
    pos = [3.75, 2.5, 3.75]
    rot = [0.0, -90.0, 0.0]

[[obj]]
    id = "sovsh_ceil01"
    pos = [6.25, 2.5, 1.25]
    rot = [0.0, 90.0, 0.0]

[[obj]]
    id = "sovsh_ceil01"
    pos = [6.25, 2.5, 3.75]
    rot = [0.0, 0.0, 0.0]

# ------ Walls ------
# Room 1
[[obj]]
    id = "sovsh_wall"
    pos = [0.0, 0.0, 1.25]
    rot = [0.0, -90.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [0.0, 0.0, 3.75]
    rot = [0.0, -90.0, 0.0]

[[obj]]
    id = "sovsh_wall_dr02"
    pos = [1.25, 0.0, 0.0]
    rot = [0.0, 180.0, 0.0]

[[obj]]
    id = "sovsh_door_herm01"
    pos = [1.25, 0.0, 0.0]
    rot = [0.0, 180.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [3.75, 0.0, 0.0]
    rot = [0.0, 180.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [6.25, 0.0, 0.0]
    rot = [0.0, 180.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [1.25, 0.0, 5.0]
    rot = [0.0, 0.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [3.75, 0.0, 5.0]
    rot = [0.0, 0.0, 0.0]

[[obj]]
    id = "sovsh_wall_dr01"
    pos = [6.25, 0.0, 5.0]
    rot = [0.0, 0.0, 0.0]

[[obj]]
    id = "sovsh_door_herm02"
    pos = [6.25, 0.0, 5.0]
    rot = [0.0, 0.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [7.5, 0.0, 1.25]
    rot = [0.0, 90.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [7.5, 0.0, 3.75]
    rot = [0.0, 90.0, 0.0]

# Room 2

[[obj]]
    id = "sovsh_wall"
    pos = [3.75, 0.0, 10.4]
    rot = [0.0, 0.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [6.25, 0.0, 10.4]
    rot = [0.0, 0.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [3.75, 0.0, 5.4]
    rot = [0.0, 180.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [7.5, 0.0, 6.65]
    rot = [0.0, 90.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [7.5, 0.0, 9.15]
    rot = [0.0, 90.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [2.5, 0.0, 6.65]
    rot = [0.0, -90.0, 0.0]

[[obj]]
    id = "sovsh_wall"
    pos = [2.5, 0.0, 9.15]
    rot = [0.0, -90.0, 0.0]

# ------ Machinery & Pipes -----
[[obj]]
    id = "diesel_gen"
    pos = [2.7, 0.0, 3.7]

[[obj]]
    id = "diesel_gen_pipes"
    pos = [0.83, 1.63, 4.23]
    rot = [0.0, 180.0, 0.0]

[[obj]]
    id = "pipes_asm2x2"
    pos = [2.5, 0.0, 2.5]
    rot = [0.0, 180.0, 0.0]

# ------ Furniture -----
# [[obj]]
#     id = "chair"
#     pos = [0.5, 0.0, 3.0]
#     rot = [0.0, 122.0, 0.0]

[[obj]]
    id = "metal_locker03"
    pos = [0.07, 0.0, 0.91]
    rot = [0.0, 92.0, 0.0]

[[obj]]
    id = "metal_locker01"
    pos = [0.07, 0.0, 1.45]
    rot = [0.0, 90.0, 0.0]

[[obj]]
    id = "metal_locker02"
    pos = [0.07, 0.0, 2.3]
    rot = [0.0, 87.0, 0.0]

[[obj]]
    id = "table01"
    pos = [6.7, 0.0, 0.4]

[[obj]]
    id = "vodka"
    pos = [6.2, 1.2, 0.9]