
[window]
  title = "Interlope Engine"
  width = 1680
  height = 1050
  fullsc = true
  # width = 1366
  # height = 768
  # fullsc = false
  xpos = 0
  ypos = 0
  border = false
  vsync = false
  max_framerate = 120.0

[graphics]
  wireframe = false

[path]
  shaders = "shaders/"
  meshes = "assets/meshes/"
  textures = "assets/textures/"

  objects_data = "data/objects.json"
  scenes_data = "data/scenes/test.json"
